<article class="content-article" style="height: 85%; display: flex;flex-direction: column;">
    <h1 style="margin-bottom: 10px">
        Planning de stream du groupe
    </h1>
    <div style="flex: 1;">
        <iframe class="agenda-google" src="https://calendar.google.com/calendar/embed?src=24df3fd4159ebadc623d37c7d2b3c9075cf6c08727664de97b2dd7a54d6415f2%40group.calendar.google.com&ctz=Europe%2FParis" style="border: 0" frameborder="0" scrolling="no"></iframe>
    </div><br>
    <div class="d-flex" style="margin-top: 25px">
        <a target="_bank" href="https://calendar.google.com/calendar/u/0?cid=MjRkZjNmZDQxNTllYmFkYzYyM2QzN2M3ZDJiM2M5MDc1Y2Y2YzA4NzI3NjY0ZGU5N2IyZGQ3YTU0ZDY0MTVmMkBncm91cC5jYWxlbmRhci5nb29nbGUuY29t" class="btn btn-primary" style="width: 100%;margin: 0px 10px">Importer sur google</a>
<!--        <a target="_bank" href="" class="btn btn-primary" style="width: 100%;margin: 0px 10px">Téléchargé ()</a>-->

    </div>
</article>