<?php global $user; ?>

<article class="content-article" style="height: 80%; margin-bottom: 60px">
    <h1>
        Ici vous allez pouvoir gerez l'overlays de sponsor
    </h1>
    <br><br>
    <h2>
        Gerez votre overlays !
    </h2>
    <small>La taille ne peut pas être gerez par obs</small>

    <h6>Width: <input type="number" id="widthInput" placeholder="800"></h6>
    <h6>Height: <input type="number" id="heightInput" placeholder="600"></h6>

    <h3>
        Lien de l'overlays:
    </h3>
    <br>

<?php if ($_SESSION['modeStream'] === "true"){ ?>
    <a>
        https://*****.**/********/?**=***&<span id="dimensionsOutput">width=800&height=600</span>
    </a>
<?php } else { ?>
    <a id="linkOver" href="<?= $_SERVER['REQUEST_SCHEME']?>://<?= $_SERVER['HTTP_HOST']?>/OverlayStream-Vturias/overlay/?id=<?= $user->id ?>&" data-url="<?= $_SERVER['REQUEST_SCHEME']?>://<?= $_SERVER['HTTP_HOST']?>/OverlayStream-Vturias/overlay/?id=<?= $user->id ?>&">
        <?= $_SERVER['REQUEST_SCHEME']?>://<?= $_SERVER['HTTP_HOST']?>/overlay/?id=<?= $user->id ?>&<span id="dimensionsOutput">width=800&height=600</span>
    </a>
<?php }?>
    <br><br>

    <iframe
        style="border: unset;width: 100%;height: 700px"
        src="../overlay/?width=800&height=600&id=<?= $user->id ?>"
    >
    </iframe>


</article>
<script src="../assets/overlays.js"></script>