<div class="up">
    <div class="left">

        <div class="article-tyrolium">
            <div class="article-padding">
                <h1>Hey la commu de : </h1><br>
                <h1 class="blue"><?= $user->displayName ?> </h1>
            </div>
        </div>

    </div>

    <div class="right">
        <div class="img"></div>
    </div>
</div>

<div class="down">

    <div class="article-tyrolium">
        <div class="article-padding" style="text-align: center">
            <h1>Pensez à Tyrolium pour créer un site internet !</h1><br>
            <h1>Go : <b class="blue">https://tyrolium.fr</b></h1>
        </div>
    </div>
</div>