<?php

global $showSponsoAll;
global $width;
global $height;

?>


<?php
if ($showSponsoAll){

    $i = 0;
    foreach ($showSponsoAll as $sponso){
        $i++
?>

        <link rel='stylesheet' href='<?= $sponso->styleUrl . "/" . $sponso->styleUrl . ".css" ?>'>
        <article class="article <?php if ($i == 1){ echo "visible"; } ?>" id="<?= $sponso->styleUrl ?>">

            <?php require_once $sponso->styleUrl . "/" . $sponso->styleUrl . ".phtml"; ?>

        </article>

<?php } } ?>



<style>

    article{
        width: <?= $width ?>px;
        height: <?= $height ?>px;
        position: absolute;
        top: 0;
        left: 0;
        transition: opacity 1s ease-in-out;
        /*background-color: red;*/
    }

    .article {
        opacity: 0;
    }

    .visible {
        opacity: 1;
        pointer-events: auto;
    }

</style>

<script>
    var articles = document.querySelectorAll('.article');
    var currentArticleIndex = 0;

    function switchArticles() {
        articles.forEach((article, index) => {
            if (index === currentArticleIndex) {
                article.classList.add('visible');
            } else {
                article.classList.remove('visible');
            }
        });

        currentArticleIndex = (currentArticleIndex + 1) % articles.length;
    }

    setInterval(switchArticles, 10000);
</script>