<?php

global $sponso;
global $width;
global $height;
global $user;

?>


<?php if ($sponso){ ?>

        <link rel='stylesheet' href='<?= $sponso->styleUrl . "/" . $sponso->styleUrl . ".css" ?>'>
        <article class="article" id="<?= $sponso->styleUrl ?>">

            <?php require_once $sponso->styleUrl . "/" . $sponso->styleUrl . ".phtml"; ?>

        </article>

<?php } ?>



<style>

    <?php if ($isDev == true){ ?>

    article{
        width: 100%;
        height: 100%;
        /*position: absolute;*/
        /*top: 0;*/
        /*left: 0;*/
        transition: opacity 1s ease-in-out;
        /*background-color: red;*/
    }



     <?php } else { ?>

    article{
        width: <?= $width ?>px;
        height: <?= $height ?>px;
        position: absolute;
        top: 0;
        left: 0;
        transition: opacity 1s ease-in-out;
        /*background-color: red;*/
    }

    <?php } ?>

    .article {
        opacity: 1;
        pointer-events: auto;
    }

</style>